---
- name: Install Haproxy on local hosts
  notify: Enable Haproxy Service
  become: true
  block:
    - name: Install Haproxy
      ansible.builtin.apt:
        state: present
        name: haproxy
        update_cache: true

    - name: Add haproxy bin dir to system-wide $PATH
      ansible.builtin.copy:
        dest: /usr/bin
        src: /usr/sbin/haproxy
        mode: 0751

    - name: Initialize Haproxy Config
      ansible.builtin.template:
        mode: 0700
        src: haproxy.cfg.j2
        dest: /etc/haproxy/haproxy.cfg

    - name: Set haproxy config directory
      ansible.builtin.command:
        cmd: haproxy -f {{ haproxy_config_dir }}
        # changed_when: false
