---
- name: Install Haproxy on local hosts
  notify: Enable Haproxy Service
  become: true
  block:
    - name: Install Haproxy
      ansible.builtin.apt:
        state: present
        name: haproxy
        update_cache: true

    - name: Initialize Haproxy Config
      ansible.builtin.template:
        mode: "700"
        src: haproxy.cfg.j2
        dest: /etc/haproxy/haproxy.cfg
