---
- name: Install rke2-server
  become: true
  block:
    - name: Download rke2 script
      ansible.builtin.get_url:
        owner: root
        mode: "700"
        dest: /home/{{ user }}/rke2-server
        url: https://get.rke2.io

    - name: Create Config Folder
      ansible.builtin.file:
        mode: "700"
        path: /etc/rancher/rke2
        state: directory

    - name: Set rke2 config
      ansible.builtin.template:
        mode: "700"
        src: rke2-config.j2
        dest: /etc/rancher/rke2/config.yaml

    - name: Run rke2 script
      ansible.builtin.command:
        chdir: /home/{{ user }}/
        cmd: sh rke2-server
      register: output
      changed_when: output.rc !=0

    - name: Delete Rke2 script file
      become: true
      ansible.builtin.file:
        state: absent
        path: /{{ user }}/rke2-server

- name: Run primary server service
  become: true
  when: master | bool
  block:
    - name: Start rke2-server service
      become: true
      ansible.builtin.service:
        name: rke2-server
        state: started
        enabled: true

    - name: Wait for port 9345 to become open on the host
      ansible.builtin.wait_for:
        host: control-plane-1
        port: 9345

- name: Run secondary server service
  become: true
  when: not master | bool
  ansible.builtin.service:
    name: rke2-server
    state: started
    enabled: true
