---
- name: Install rancher admin
  hosts: localhost
  roles:
    - apps/rancher

- name: Install storage proviser (longhorn)
  hosts: localhost
  roles:
    - apps/storage

- name: Deploy Airflow stack
  hosts: localhost
  roles:
    - apps/airflow
