---
- name: Install haproxy
  hosts: localhost
  roles:
    - prerequises/haproxy

- name: Install open iscsi
  hosts: k8s
  roles:
    - prerequises/open_iscsi

- name: Install open iscsi
  hosts: localhost
  roles:
    - prerequises/modules
