---
- name: Create Airflow namespace
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: "{{ release_namespace }}"

- name: Get host private key
  ansible.builtin.command:
    cmd: cat {{ pr_key_file }}
  register: output2
  changed_when: output2.rc != 0

- name: Create Secret with machine private key
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      type: Opaque
      data:
        gitSshKey: "{{ output2.stdout | b64encode }}"
      metadata:
        name: "{{ sshKeySecret }}"
        namespace: "{{ release_namespace }}"

- name: Get host public key
  ansible.builtin.command:
    cmd: cat {{ pr_key_file }}.pub
  register: output3
  changed_when: output3.rc != 0

- name: Confirmation de la copie de la clé ssh sur le compte github
  ansible.builtin.pause:
    prompt: |

      {{ output3.stdout }}

      Assurer-vous d'ajouter la clé ci-dessus sur votre compte github pour créer la connection avec Airflow.
      Une fois ceci fait, appuyer entrer pour continuer l'installation.
