---
- name: Install cert manager CRDs
  ansible.builtin.command:
    cmd: kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/{{ chart_version }}/cert-manager.crds.yaml

- name: Add the Jetstack Helm repository
  ansible.builtin.command:
    cmd: helm repo add jetstack https://charts.jetstack.io

- name: Update your local Helm chart repository cache
  ansible.builtin.command:
    cmd: helm repo update

- name: Install the cert-manager Helm chart
  ansible.builtin.command:
    cmd: helm install {{ release_name }} jetstack/cert-manager --namespace {{ release_namespace }} --create-namespace --replace --version {{ chart_version }}
