---
- name: Deploy Rancher UI Admin
  when: install_rancher
  block:
    - name: Add the Rancher Helm repository
      kubernetes.core.helm_repository:
        name: rancher-stable
        repo_url: "https://releases.rancher.com/server-charts/stable"

    - name: Install the rancher Helm chart
      kubernetes.core.helm:
        name: "{{ release_name }}"
        chart_ref: rancher-stable/rancher
        release_namespace: "{{ release_namespace }}"
        create_namespace: true
        update_repo_cache: true
        values:
          hostname={{ rancher_hostname }}
          bootstrapPassword={{ rancher_bootstrapPassword }}
          ingress.tls.source={{ rancher_ingress_tls_source }}
          letsEncrypt.email={{ rancher_letsEncrypt_email }}
          letsEncrypt.ingress.class={{ rancher_letsEncrypt_ingress_class }}
          letsEncrypt.environment={{ rancher_letsEncrypt_env }}
