---
- name: Add the Rancher Helm repository
  ansible.builtin.command:
    cmd: helm repo add rancher-stable https://releases.rancher.com/server-charts/stable

- name: Update your local Helm chart repository cache
  ansible.builtin.command:
    cmd: helm repo update

- name: Install the rancher Helm chart
  ansible.builtin.command:
    cmd: |
      helm install {{ release_name }} rancher-stable/rancher
      --namespace {{ release_namespace }}
      --create-namespace
      --replace
      --set hostname={{ rancher_hostname }}
      --set bootstrapPassword={{ rancher_bootstrapPassword }}
      --set ingress.tls.source={{ rancher_ingress_tls_source }}
      --set letsEncrypt.email={{ rancher_letsEncrypt_email }}
      --set letsEncrypt.ingress.class={{ rancher_letsEncrypt_ingress_class }}
