---
- name: Install pip3
  become: true
  ansible.builtin.apt:
    name: python3-pip
    state: present

- name: Install module python kubernetes
  ansible.builtin.pip:
    name: kubernetes

- name: Install collection kubernetes.core
  ansible.builtin.command:
    cmd: ansible-galaxy collection install kubernetes.core