---
release_name: "rancher"
release_namespace: "cattle-system"
rancher_hostname: "{{ loadbalancer_public_address }}.sslip.io"
rancher_bootstrapPassword: dimanche54
rancher_ingress_tls_source: letsEncrypt
rancher_letsEncrypt_email: edy.koffi@data3354.com
rancher_letsEncrypt_ingress_class: haproxy