---
- name: Debug info
  ansible.builtin.debug:
    msg: Handler ok

- name: Start rke2-server service
  become: true
  ansible.builtin.service:
    name: rke2-server
    state: restarted
    enabled: true
