---
- name: Install Haproxy on local hosts
  notify: Enable Haproxy Service
  become: true
  block:
    - name: Install Haproxy on Debian system
      when: ansible_facts['os_family'] == "Debian"
      ansible.builtin.apt:
        state: present
        name: haproxy

    - name: Install Haproxy on RedHat system
      when: ansible_facts['os_family'] == "RedHat"
      ansible.builtin.yum:
        state: present
        name: haproxy

    - name: Add haproxy bin dir to system-wide $PATH
      ansible.builtin.copy:
        dest: /usr/bin
        src: /usr/sbin/haproxy
        mode: 0751

    - name: Initialize Haproxy Config
      ansible.builtin.template:
        mode: 0700
        src: haproxy.cfg.j2
        dest: /etc/haproxy/haproxy.cfg

    - name: Set haproxy config directory
      ansible.builtin.command:
        cmd: haproxy -f {{ haproxy_config_dir }}

    - name: Set authorized keys
      ansible.builtin.authorized_key:
        user: "{{ user }}"
        state: present
        key: "{{ item.key }}"
      with_items: "{{ authorized_keys }}"
