---
- name: Deploy Kube-prometheus-stack
  when: install_monitoring
  block:
    - name: Add the rancher-charts Helm repository
      kubernetes.core.helm_repository:
        name: rancher-charts
        repo_url: "https://git.rancher.io/charts"

    - name: Install the rancher-monitoring Helm chart
      kubernetes.core.helm:
        name: "{{ release_name }}"
        chart_ref: rancher-charts/rancher-monitoring
        release_namespace: "{{ release_namespace }}"
        create_namespace: true
        update_repo_cache: true
        values:
          prometheus.prometheusSpec.evaluationInterval=1m
          prometheus.prometheusSpec.retentionSize=50GiB
          prometheus.prometheusSpec.scrapeInterval=1m
          rke2ControllerManager.enabled=true
          rke2Scheduler.enabled=true
          rke2Proxy.enabled=true
          rke2IngressNginx.enabled=true
          rke2Etcd.enabled=true
